java_test(
    name = "HelloTest",
    srcs = ["HelloTest.java"],
    deps = [
        "//java/com/systemlogic/sample:hello",
        "//external:com_google_truth-jar",
        "//external:com_google_guava-jar",
        "//external:com_googlecode_java_diff_utils-jar"
    ]
)
