java_test(
    name = "HelloTest",
    srcs = ["HelloTest.java"],
    deps = [
        "//java/com/systemlogic/sample:hello",
        "@com_google_truth//jar",
        "@com_google_guava//jar",
        "@com_googlecode_java_diff_utils//jar"
    ]
)
