language: java
dist: trusty
sudo: required
#cache:
#  directories:
#  - .autoconf
#  - $HOME/.cache
services:
- docker
before_install:
- git checkout master
- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
- git fetch --force origin refs/notes/*:refs/notes/*
- git fetch
- git branch -r
- git checkout $TRAVIS_PULL_REQUEST_BRANCH
- git pull origin  $TRAVIS_PULL_REQUEST_BRANCH
install: true
script:
- source environment.bash
- changedFileSet=$(git diff --name-only origin/master..origin/${TRAVIS_PULL_REQUEST_BRANCH} )
- /bin/echo "Changed Files Are"
- /bin/echo $changedFileSet |  xargs -n1
- testTargets=$(bazel query "kind('.*_test rule', rdeps(set(//...), set(${changedFileSet}) ))")
- /bin/echo "Affected Test Cases"
- /bin/echo $testTargets |  xargs -n1
- if [$testTargets -gt 0]; then bazel test $testTargets ; fi
- buildTargets=$(bazel query "kind('_library|_binary', rdeps(set(//...), set(${changedFileSet}) ))")
- /bin/echo "Affected Builds"
- /bin/echo $buildTargets |  xargs -n1
- if [$buildTargets -gt 0]; then bazel build $buildTargets ; fi
