java_test(
    name = "HelloTest",
    srcs = [
        "HelloTest.java",
    ],
    deps = [
        "//external:junit-jar",
        "//external:visible_assertions-jar",
        "//java/com:helloLib"
    ],
)
