package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_library")

# label would be //go/B:lib-b
go_library(
    name = "lib-b",
    srcs = ["lib_b.go"],
    importpath = "github.systemlogic.com/systemlogic/intro-to-bazel/go/B",
    deps = []
)
