package(default_visibility = ["//visibility:public"])

java_library(
    name = "HelloWorld",
    srcs = [
        "HelloWorld.java",
    ],
    deps = [
        "//external:javax_servlet_api-jar",
    ],
)
