package(default_visibility = ["//visibility:public"])

java_library(
    name = "controller",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/common/connection",
        "//java/com/common/mapper",
        "//java/com/common/model",
        "//external:servlet_api-jar",
        "//external:spring_beans-jar",
        "//external:spring_context-jar",
        "//external:spring_tx-jar",
        "//external:spring_web-jar",
        "//external:spring_webmvc-jar",
    ],
)
