apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: "mongo"
 replicas: 1
 selector:
    matchLabels:
      app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: index.docker.io/library/mongo:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 27017
         resources:
           limits:
             cpu: 100m
             memory: 200Mi
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
     volumes:
       - name: mongo-persistent-storage
         persistentVolumeClaim:
           claimName: pv-claim-harora37  #replace with pv-claim-<namespace>
     imagePullSecrets:
        - name: artifactory-registry-secret
---
apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
 name: mongo
spec:
    ports:
    - name: driver
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: https
      port: 28017
      protocol: TCP
      targetPort: 28017
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
    selector:
      app: mongo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: mongo
spec:
  rules:
  - host: mongo.localhost
    http:
      paths:
      - backend:
          serviceName: mongo
          servicePort: 28017
