apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-harora37
#  namespace: harora37
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 4Gi
