apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-harora37
#  namespace: harora37
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
