package(default_visibility = ["//visibility:public"])

java_library(
    name = "connection",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/common/mapper",
        "//java/com/common/mapper:emp_dept.jar",
        "//java/com/common/model",
        "//external:spring_beans-jar",
        "//external:spring_context-jar",
        "//external:spring_jdbc-jar",
    ],
)
