package(default_visibility = ["//visibility:public"])

java_library(
    name = "connection",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/common/mapper",
        "//java/com/common/mapper:emp_dept.jar",
        "//java/com/common/model",
        "@spring_beans//jar",
        "@spring_context//jar",
        "@spring_jdbc//jar",
    ],
)
